/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.indicadores;

/**
 *
 * @author Admin
 */
public class IndicadorGrupoPanel extends javax.swing.JPanel {

    /**
     * Creates new form IndicadorGrupoPanel
     */
    public IndicadorGrupoPanel() {
        initComponents();
    }
    
    String grupoNome;
    int rows;
    public IndicadorGrupoPanel(String nome, String[] items) {
        grupoNome = nome;
        this.rows = items.length;
        initComponents();
        for (String name : items) {
            IndicadorItemPanel item = new IndicadorItemPanel(name);
            itemsPanel.add(item);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblGrupoNome = new javax.swing.JLabel();
        itemsPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblNumGrupo = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblGrupoNome.setText(grupoNome      );
        jPanel1.add(lblGrupoNome, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel1, gridBagConstraints);

        itemsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        itemsPanel.setLayout(new java.awt.GridLayout(rows, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 286;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(itemsPanel, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.GridBagLayout());

        lblNumGrupo.setText("Nº");
        jPanel5.add(lblNumGrupo, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jPanel5, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblGrupoNome;
    private javax.swing.JLabel lblNumGrupo;
    // End of variables declaration//GEN-END:variables
}
