/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.isa.view;

import com.mycompany.isa.ISA;
import com.mycompany.isa.model.Lote;
import com.mycompany.isa.utility.DataTransfer;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naoki
 */
public class CrudLote extends javax.swing.JFrame {

//    List<Lote> loteList = new ArrayList<>();
    int indice = 0;
    
    public CrudLote() {
        initComponents();
        atualizarBotoes();
        if (! ISA.loteList.isEmpty()) {
            preencherTabela();
            tabLote.changeSelection(indice, 1, false, false);
        }
        atualizarCbox();
    }
    
    private void atualizarBotoes() {      
        btnRemover.setEnabled(indice!=-1);
        btnEditar.setEnabled(indice!=-1);
    }
    
    private void preencherTabela() {
        
        DefaultTableCellRenderer cellRender = new DefaultTableCellRenderer();
        tabLote.getColumnModel().getColumn(0).setPreferredWidth(100);  //Preferencia de largura medidad em pixels
        tabLote.getColumnModel().getColumn(1).setPreferredWidth(100);  
        tabLote.getColumnModel().getColumn(2).setPreferredWidth(75);  
        tabLote.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabLote.getColumnModel().getColumn(4).setPreferredWidth(100);
        for (int i=0; i<tabLote.getColumnCount(); i++)
            tabLote.getColumnModel().getColumn(i).setCellRenderer(cellRender);
        
        DefaultTableModel modelo = (DefaultTableModel) tabLote.getModel();
        modelo.setNumRows(0);
        for (Lote lote: ISA.loteList) {
            modelo.addRow(new Object[]{
                lote.getAssentamento(),
                lote.getResponsavel(), 
                lote.getNumParcela(), 
                lote.getContato(), 
                Arrays.toString(lote.getCoordenada())
            });
        }
    }
    
    private void atualizarCbox() {
        cboxAssentamento.removeAllItems();
        for (Lote lote : ISA.loteList) {
            boolean isReapeted = false;
            for (int i = 0; i < cboxAssentamento.getItemCount(); i++) {
                if (cboxAssentamento.getItemAt(i).equals(lote.getAssentamento())) {
                    isReapeted = true;
                    break;
                }
            }
            if (!isReapeted) {
                cboxAssentamento.addItem(lote.getAssentamento());
                cboxAssentamento_editar.addItem(lote.getAssentamento());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogEditar = new javax.swing.JDialog();
        txtNome_editar = new javax.swing.JTextField();
        btnAddAssentamento_editar = new javax.swing.JButton();
        txtNumParcela_editar = new javax.swing.JTextField();
        txtContato_editar = new javax.swing.JFormattedTextField();
        btnSalvar_editar = new javax.swing.JButton();
        btnCancelar_editar = new javax.swing.JButton();
        panelCoordenada_editar = new javax.swing.JPanel();
        lblCoordenadaX_editar = new javax.swing.JLabel();
        lblCoordenadaY_editar = new javax.swing.JLabel();
        txtCoordenadaX_editar = new javax.swing.JFormattedTextField();
        txtCoordenadaY_editar = new javax.swing.JFormattedTextField();
        cboxAssentamento_editar = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        lblCadTitulo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblErro = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        scrollTabela = new javax.swing.JScrollPane();
        tabLote = new javax.swing.JTable();
        txtNumParcela = new javax.swing.JTextField();
        txtContato = new javax.swing.JFormattedTextField();
        btnLimpar = new javax.swing.JButton();
        panelCoordenada = new javax.swing.JPanel();
        lblCoordenadaX = new javax.swing.JLabel();
        lblCoordenadaY = new javax.swing.JLabel();
        txtCoordenadaX = new javax.swing.JFormattedTextField();
        txtCoordenadaY = new javax.swing.JFormattedTextField();
        cboxAssentamento = new javax.swing.JComboBox<>();
        btnAddAssentamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        standartMenuBar1 = new com.mycompany.isa.components.StandartMenuBar();

        dialogEditar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogEditar.setTitle("Editar");
        dialogEditar.setResizable(false);

        txtNome_editar.setBorder(javax.swing.BorderFactory.createTitledBorder("Responsavel"));

        btnAddAssentamento_editar.setText("Adicionar assentamento");
        btnAddAssentamento_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAssentamento_editarActionPerformed(evt);
            }
        });

        txtNumParcela_editar.setBorder(javax.swing.BorderFactory.createTitledBorder("Nº da parcela"));

        txtContato_editar.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));
        try {
            txtContato_editar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSalvar_editar.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        btnSalvar_editar.setText("Salvar");
        btnSalvar_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar_editarActionPerformed(evt);
            }
        });

        btnCancelar_editar.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        btnCancelar_editar.setText("Cancelar");
        btnCancelar_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_editarActionPerformed(evt);
            }
        });

        panelCoordenada_editar.setBackground(txtNome.getBackground());
        panelCoordenada_editar.setBorder(javax.swing.BorderFactory.createTitledBorder("Coordenadas"));

        lblCoordenadaX_editar.setText("Latitude");

        lblCoordenadaY_editar.setText("Longitude");

        txtCoordenadaX_editar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00000"))));

        txtCoordenadaY_editar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00000"))));

        javax.swing.GroupLayout panelCoordenada_editarLayout = new javax.swing.GroupLayout(panelCoordenada_editar);
        panelCoordenada_editar.setLayout(panelCoordenada_editarLayout);
        panelCoordenada_editarLayout.setHorizontalGroup(
            panelCoordenada_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoordenada_editarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCoordenadaX_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCoordenadaX_editar, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCoordenadaY_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCoordenadaY_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCoordenada_editarLayout.setVerticalGroup(
            panelCoordenada_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoordenada_editarLayout.createSequentialGroup()
                .addGroup(panelCoordenada_editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoordenadaX_editar)
                    .addComponent(lblCoordenadaY_editar)
                    .addComponent(txtCoordenadaX_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoordenadaY_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboxAssentamento_editar.setBorder(javax.swing.BorderFactory.createTitledBorder("Assentamento"));

        javax.swing.GroupLayout dialogEditarLayout = new javax.swing.GroupLayout(dialogEditar.getContentPane());
        dialogEditar.getContentPane().setLayout(dialogEditarLayout);
        dialogEditarLayout.setHorizontalGroup(
            dialogEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEditarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(dialogEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtContato_editar)
                    .addComponent(txtNome_editar)
                    .addComponent(txtNumParcela_editar)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogEditarLayout.createSequentialGroup()
                        .addComponent(btnSalvar_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCoordenada_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxAssentamento_editar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAssentamento_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        dialogEditarLayout.setVerticalGroup(
            dialogEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEditarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cboxAssentamento_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAssentamento_editar)
                .addGap(18, 18, 18)
                .addComponent(txtNome_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNumParcela_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContato_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCoordenada_editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar_editar)
                    .addComponent(btnCancelar_editar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Lotes");
        setResizable(false);

        txtNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Responsável"));

        lblCadTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCadTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadTitulo.setText("Gerenciar Lotes");

        btnSalvar.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblErro.setForeground(new java.awt.Color(255, 0, 51));

        btnRemover.setFont(new java.awt.Font("Quicksand Medium", 0, 14)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        scrollTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabLote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assentamento", "Responsável", "Nº da Parcela", "Contato", "Coordenada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabLote.setFocusable(false);
        tabLote.setShowGrid(false);
        tabLote.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabLoteMouseClicked(evt);
            }
        });
        tabLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabLoteKeyReleased(evt);
            }
        });
        scrollTabela.setViewportView(tabLote);

        txtNumParcela.setBorder(javax.swing.BorderFactory.createTitledBorder("Nº da Parcela"));

        txtContato.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));
        try {
            txtContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        panelCoordenada.setBackground(txtNome.getBackground());
        panelCoordenada.setBorder(javax.swing.BorderFactory.createTitledBorder("Coordenadas"));

        lblCoordenadaX.setText("Latitude");

        lblCoordenadaY.setText("Longitude");

        txtCoordenadaX.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00000"))));

        txtCoordenadaY.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00000"))));

        javax.swing.GroupLayout panelCoordenadaLayout = new javax.swing.GroupLayout(panelCoordenada);
        panelCoordenada.setLayout(panelCoordenadaLayout);
        panelCoordenadaLayout.setHorizontalGroup(
            panelCoordenadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoordenadaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCoordenadaX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCoordenadaX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCoordenadaY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCoordenadaY)
                .addContainerGap())
        );
        panelCoordenadaLayout.setVerticalGroup(
            panelCoordenadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCoordenadaLayout.createSequentialGroup()
                .addGroup(panelCoordenadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoordenadaX)
                    .addComponent(lblCoordenadaY)
                    .addComponent(txtCoordenadaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCoordenadaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboxAssentamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Assentamento"));

        btnAddAssentamento.setText("Adicionar assentamento");
        btnAddAssentamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAssentamentoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adicionar lote");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNome)
                            .addComponent(txtNumParcela)
                            .addComponent(txtContato)
                            .addComponent(panelCoordenada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboxAssentamento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddAssentamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCadTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(lblErro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(615, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditar, btnRemover});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLimpar, btnSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblCadTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxAssentamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddAssentamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCoordenada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemover)
                    .addComponent(btnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(lblErro)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );

        setJMenuBar(standartMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // check null fields
        if (txtNome.getText().isBlank() |
            txtNumParcela.getText().isBlank() ||
            txtContato.getText().isBlank() ||
            txtCoordenadaX.getText().isBlank() ||
            txtCoordenadaY.getText().isBlank() ||
            cboxAssentamento.getSelectedIndex() < 0
        ) {
            JOptionPane.showMessageDialog(
                this, "Preencha todos os campos", 
                "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
        Lote lote = new Lote();
        
        lote.setAssentamento((String) cboxAssentamento.getSelectedItem());
        lote.setResponsavel(txtNome.getText());
        lote.setNumParcela(txtNumParcela.getText());
        lote.setContato(txtContato.getText());
        double x = Double.parseDouble(txtCoordenadaX.getText().replace(',','.'));
        double y = Double.parseDouble(txtCoordenadaY.getText().replace(',', '.'));
        lote.setCoordenada(new double[] {x, y});
        ISA.loteList.add(lote);
        DataTransfer.exportLote(lote);
        
        indice = ISA.loteList.size()-1;
        preencherTabela();
        tabLote.changeSelection(indice, 1, false, false);
        atualizarBotoes();
        btnLimparActionPerformed(evt);
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    int editing_row;
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editing_row = tabLote.getSelectedRow();
        Lote lote = ISA.loteList.get(editing_row);
        
        
        txtNome_editar.setText(lote.getResponsavel());
        txtNumParcela_editar.setText(lote.getNumParcela());
        txtContato_editar.setText(lote.getContato());
        txtCoordenadaX_editar.setText(String.valueOf(lote.getCoordenada()[0]));
        txtCoordenadaY_editar.setText(String.valueOf(lote.getCoordenada()[1]));
        
        dialogEditar.setSize(390, 415);
        dialogEditar.setLocationRelativeTo(null);
        dialogEditar.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        if (0!=JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir?", "Confirmar exclusão", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION)) {
            return;
        }
        ISA.loteList.remove(indice);
        DataTransfer.deleteLotes();
        DataTransfer.exportAllLotes(ISA.loteList);
        indice += (indice>0 || ISA.loteList.isEmpty()) ? -1 : 0;
        preencherTabela();
        tabLote.changeSelection(indice, 1, false, false);
        atualizarBotoes();

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void tabLoteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabLoteMouseClicked
        indice = tabLote.getSelectedRow();
        atualizarBotoes();
    }//GEN-LAST:event_tabLoteMouseClicked

    private void tabLoteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabLoteKeyReleased
        indice = tabLote.getSelectedRow();
        atualizarBotoes();
    }//GEN-LAST:event_tabLoteKeyReleased

    private void btnSalvar_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar_editarActionPerformed
        // check null fields
        if (cboxAssentamento_editar.getSelectedItem().toString().isBlank() ||
            txtNome_editar.getText().isBlank() ||
            txtNumParcela_editar.getText().isBlank() ||
            txtContato_editar.getText().isBlank() ||
            txtCoordenadaX_editar.getText().isBlank() ||
            txtCoordenadaY_editar.getText().isBlank()
        ) {
            JOptionPane.showMessageDialog(
                this, "Preencha todos os campos", 
                "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Lote lote = new Lote();
        lote.setAssentamento(cboxAssentamento_editar.getSelectedItem().toString());
        lote.setResponsavel(txtNome_editar.getText());
        lote.setNumParcela(txtNumParcela_editar.getText());
        lote.setContato(txtContato_editar.getText());
        double x = Double.parseDouble(txtCoordenadaX_editar.getText().replace(',','.'));
        double y = Double.parseDouble(txtCoordenadaY_editar.getText().replace(',','.'));
        lote.setCoordenada(new double[] {x, y});
        
        ISA.loteList.remove(editing_row);
        ISA.loteList.add(editing_row, lote);
        DataTransfer.deleteLotes();
        DataTransfer.exportAllLotes(ISA.loteList);
        preencherTabela();
        dialogEditar.dispose();
    }//GEN-LAST:event_btnSalvar_editarActionPerformed

    private void btnCancelar_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_editarActionPerformed
        dialogEditar.dispose();
    }//GEN-LAST:event_btnCancelar_editarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtNome.setText("");
        txtNumParcela.setText("");
        txtContato.setText("");
        txtCoordenadaX.setText("");
        txtCoordenadaY.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAddAssentamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAssentamentoActionPerformed
        String assentamento = JOptionPane.showInputDialog(this, "Digite o nome do assentamento", "Novo Assentamento", JOptionPane.PLAIN_MESSAGE);
        assentamento = assentamento.trim();
        if (assentamento.isBlank()) {
            return;
        }
        boolean isReapeted = false;
        for (int i = 0; i < cboxAssentamento.getItemCount(); i++) {
            if (cboxAssentamento.getItemAt(i).equals(assentamento)) {
                isReapeted = true;
                break;
            }
        }
        if (!isReapeted) {
            cboxAssentamento.addItem(assentamento);
            cboxAssentamento.setSelectedItem(assentamento);
            cboxAssentamento_editar.addItem(assentamento);
            cboxAssentamento_editar.setSelectedItem(assentamento);
        }
    }//GEN-LAST:event_btnAddAssentamentoActionPerformed

    private void btnAddAssentamento_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAssentamento_editarActionPerformed
        String assentamento = JOptionPane.showInputDialog(this, "Digite o nome do assentamento", "Novo Assentamento", JOptionPane.PLAIN_MESSAGE);
        boolean isReapeted = false;
        for (int i = 0; i < cboxAssentamento.getItemCount(); i++) {
            if (cboxAssentamento.getItemAt(i).equals(assentamento )) {
                isReapeted = true;
                break;
            }
        }
        if (!isReapeted) {
            cboxAssentamento.addItem(assentamento);
            cboxAssentamento_editar.addItem(assentamento);
        }
        
    }//GEN-LAST:event_btnAddAssentamento_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudLote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAssentamento;
    private javax.swing.JButton btnAddAssentamento_editar;
    private javax.swing.JButton btnCancelar_editar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar_editar;
    private javax.swing.JComboBox<String> cboxAssentamento;
    private javax.swing.JComboBox<String> cboxAssentamento_editar;
    private javax.swing.JDialog dialogEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCadTitulo;
    private javax.swing.JLabel lblCoordenadaX;
    private javax.swing.JLabel lblCoordenadaX_editar;
    private javax.swing.JLabel lblCoordenadaY;
    private javax.swing.JLabel lblCoordenadaY_editar;
    private javax.swing.JLabel lblErro;
    private javax.swing.JPanel panelCoordenada;
    private javax.swing.JPanel panelCoordenada_editar;
    private javax.swing.JScrollPane scrollTabela;
    private com.mycompany.isa.components.StandartMenuBar standartMenuBar1;
    private javax.swing.JTable tabLote;
    private javax.swing.JFormattedTextField txtContato;
    private javax.swing.JFormattedTextField txtContato_editar;
    private javax.swing.JFormattedTextField txtCoordenadaX;
    private javax.swing.JFormattedTextField txtCoordenadaX_editar;
    private javax.swing.JFormattedTextField txtCoordenadaY;
    private javax.swing.JFormattedTextField txtCoordenadaY_editar;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome_editar;
    private javax.swing.JTextField txtNumParcela;
    private javax.swing.JTextField txtNumParcela_editar;
    // End of variables declaration//GEN-END:variables
}
