/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.isa.view;

import com.mycompany.isa.ISA;
import com.mycompany.isa.model.CategoriaIndicadores;
import com.mycompany.isa.utility.JsonExporter;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.ArrayList;

import java.util.List;
import javax.swing.*;

/**
 *
 * @author naoki
 */
public class NovaCategoriaPanel extends javax.swing.JPanel {
    private CategoriaIndicadores novaCategoria = new CategoriaIndicadores();
    private List<List<JTextField>> table = new ArrayList<>();
    protected boolean editing = false;
    private int editingIndex = -1;
    /**
     * Creates new form NovoModelo
     */
    public NovaCategoriaPanel() {
        initAll();
    }
    
    private void initAll() {
        initComponents();
        atualizarTabela();
        scrollTable.getVerticalScrollBar().setUnitIncrement(10);
    }

    
    private void atualizarTabela() {
        paneTable.removeAll();
        table.clear();
        GridBagLayout layout = (GridBagLayout) paneTable.getLayout();
        GridBagConstraints c = new GridBagConstraints();
        int row = 0;
        c.anchor = GridBagConstraints.PAGE_START;
        c.fill = GridBagConstraints.HORIZONTAL;
        c.weightx = 1;
        
        
        String[][] valores = novaCategoria.getAllItemsArr();
        String[] grupo = novaCategoria.getGrupos().toArray(String[]::new);
        for (int i = 0; i < grupo.length; i++) {
            var list = new ArrayList<JTextField>();
            JTextField header = new JTextField(grupo[i]);
            loadHeaderConf(header);
            list.add(header);
            table.add(list);
            c.gridy = row++;
            paneTable.add(header, c);
            
            JTextField item = null;
            for (String valor : valores[i]) {
                item = new JTextField(valor);
                loadItemConf(item);
                list.add(item);
                c.gridy = row++;
                paneTable.add(item, c);
            }
            if (item == null) continue;
            c = layout.getConstraints(item);
            c.insets = new Insets(0, 0, 20, 0);
            layout.setConstraints(item, c);
            c.insets = new Insets(0, 0, 0, 0);
        }
        if (paneTable.getComponentCount()>0) {
            var comp = paneTable.getComponent(paneTable.getComponentCount()-1);
            if (comp != null) {
                c = layout.getConstraints(comp);
                c.weighty = 1;
                c.anchor = GridBagConstraints.FIRST_LINE_START;
                layout.setConstraints(comp, c);
            }
        }
        paneTable.updateUI();
    }
    
    
    private void atualizarCbox() {
        cboxGrupo.removeAllItems();
        cboxGrupo.addItem("<Selecionar Grupo>");
        for (String grupo : novaCategoria.getGrupos())
            cboxGrupo.addItem(grupo);
    }
    
    public void atualizarCategoriaPelaTabela() {
        String[] columnArr = new String[table.size()];
        for (int i = 0; i < table.size(); i++) {
            columnArr[i] = table.get(i).get(0).getText();
        }
        String[][] itemArr = new String[columnArr.length][];
        for (int i = 0; i < itemArr.length; i++) {
            itemArr[i] = new String[table.get(i).size()];
            for (int j = 1; j < table.get(i).size(); j++) {
                itemArr[i][j-1] = table.get(i).get(j).getText();
            }
        }
        novaCategoria = new CategoriaIndicadores(lblNome.getName(), columnArr, itemArr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        lblNovoGrupo = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        btnAddGrupo = new javax.swing.JButton();
        lblNovoIndicador = new javax.swing.JLabel();
        cboxGrupo = new javax.swing.JComboBox<>();
        txtItem = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnResetar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        scrollTable = new javax.swing.JScrollPane();
        paneTable = new javax.swing.JPanel();

        btnVoltar.setText("Voltar");

        lblNovoGrupo.setText("Novo Grupo");

        txtGrupo.setToolTipText("Adicione um grupo. Tecle enter ou pressione o botão 'Adicionar grupo à categoria'. Para deletar, clique duas vezes em um grupo ");
        txtGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrupoActionPerformed(evt);
            }
        });

        btnAddGrupo.setText("Adicionar grupo à categoria");
        btnAddGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGrupoActionPerformed(evt);
            }
        });

        lblNovoIndicador.setText("Novo Indicador");

        cboxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar Grupo>" }));

        txtItem.setToolTipText("Escreva o nome do indicador");
        txtItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemActionPerformed(evt);
            }
        });

        btnAddItem.setText("Adicionar indicador ao grupo");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnResetar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-erase-16.png"))); // NOI18N
        btnResetar.setText("Resetar");
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-windows-10-16.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Nome da Categoria");
        lblNome.setToolTipText("");

        txtNome.setToolTipText("Nome da categoria. Tecle enter para confirmar");
        txtNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        paneTable.setLayout(new java.awt.GridBagLayout());
        scrollTable.setViewportView(paneTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtItem)
                    .addComponent(cboxGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGrupo)
                    .addComponent(lblNovoGrupo)
                    .addComponent(lblNovoIndicador)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(btnVoltar)
                    .addComponent(btnResetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addComponent(scrollTable))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblNovoGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnAddGrupo)
                        .addGap(18, 18, 18)
                        .addComponent(lblNovoIndicador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btnResetar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollTable))
                .addGap(27, 27, 27))
        );

        getAccessibleContext().setAccessibleName("novoPanel");
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JButton getBtnVoltar() {
        return btnVoltar;
    }
    
    private void renameHeader(JTextField textField) {
        String oldKey = textField.getName();
        String newKey = textField.getText();
        if (oldKey.equals(newKey)) return;
        if (newKey.isBlank()) {
            novaCategoria.removeGrupo(oldKey);
        } else {
            novaCategoria.replaceGrupo(oldKey, newKey);
        }
        atualizarTabela();
        atualizarCbox();
    }
    
    private void renameItem(JTextField textField) {
        String oldValue = textField.getName();
        String newValue = textField.getText();
        String grupo = null;
        for (List<JTextField> list : table) {
            if (list.contains(textField)) {
                grupo = list.get(0).getName();
            }
        }        
        if (newValue.isBlank()) {
            novaCategoria.removeItem(grupo, oldValue);
        } else {
            novaCategoria.replaceItem(grupo, oldValue, newValue);
        }
        atualizarTabela();
    }
    
    public void carregarCategoria(CategoriaIndicadores categoria, int indice) {
        resetar();
        editing = true;
        editingIndex = indice;
        novaCategoria = new CategoriaIndicadores(categoria);
        lblNome.setText(novaCategoria.getNome());
        txtNome.setText(novaCategoria.getNome());
        atualizarCbox();
        atualizarTabela();
    }
    
    private void loadTextConf(JTextField textField) {
        textField.setName(textField.getText());
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField.setText(textField.getName());
            }
        });
    }
    private void loadHeaderConf(JTextField textField) {
        loadTextConf(textField);
        textField.setHorizontalAlignment(JTextField.CENTER);
        textField.setFont(new Font("SegoeUI", Font.BOLD, 14));
        textField.addActionListener((java.awt.event.ActionEvent evt) -> {
            renameHeader(textField);
        });
    }
    
    private void loadItemConf(JTextField textField) {
        loadTextConf(textField);
        textField.setFont(new Font("SegoeUI", Font.PLAIN, 14));
        textField.addActionListener((java.awt.event.ActionEvent evt) -> {
            renameItem(textField);
        });
    }
   
    
    protected void resetar() {
        novaCategoria = new CategoriaIndicadores();
        txtGrupo.setText("");
        txtItem.setText("");
        txtNome.setText("");
        lblNome.setText("Nome da categoria");
        cboxGrupo.removeAllItems();
        cboxGrupo.addItem("<Selecionar Grupo>");
        atualizarTabela();
    }
    private void btnAddGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGrupoActionPerformed
        if (txtGrupo.getText().isBlank()) {
            return;
        }
        String grupo = txtGrupo.getText().trim();
        if (! novaCategoria.getItemMap().containsKey(grupo)){
            txtGrupo.setText("");
            novaCategoria.addGrupo(grupo);
            cboxGrupo.addItem(grupo);
            
        }
        atualizarTabela();
    }//GEN-LAST:event_btnAddGrupoActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        String grupo = (String) cboxGrupo.getSelectedItem();
        String item = txtItem.getText().trim();
        if (novaCategoria.getItemMap().containsKey(grupo)) {
            if (! novaCategoria.getItens(grupo).contains(item)) {
                novaCategoria.addItem(grupo, item);
            }
        }
        txtItem.setText("");
        atualizarTabela();
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void txtGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrupoActionPerformed
        btnAddGrupoActionPerformed(evt);
    }//GEN-LAST:event_txtGrupoActionPerformed

    private void txtItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemActionPerformed
        btnAddItemActionPerformed(evt);
    }//GEN-LAST:event_txtItemActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (JOptionPane.showConfirmDialog(this, 
                "Tem certeza que deseja salvar?", 
                "Salvar?", 
                JOptionPane.YES_NO_OPTION)
                !=0) 
            return;
        if (novaCategoria.getNome().isBlank() ||
            novaCategoria.getGrupos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Falha ao salvar. Lembre-se de cadastrar pelo menos um grupo e preencher o nome", 
                    "Erro. Campo em branco", JOptionPane.ERROR_MESSAGE);
        } else 
        if (editing) {
            ISA.categoriaList.remove(editingIndex);
            ISA.categoriaList.add(editingIndex, novaCategoria);
            editing = false;
        } else {
            ISA.categoriaList.add(novaCategoria);
        }
        resetar();
        JsonExporter.deleteIndicadores();
        JsonExporter.exportIndicadores(ISA.categoriaList);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        if (JOptionPane.showConfirmDialog(this, 
                "Tem certeza que deseja resetar?", 
                "Resetar?", 
                JOptionPane.YES_NO_OPTION)
                !=0) 
            return;
        resetar();
    }//GEN-LAST:event_btnResetarActionPerformed

    int clickedRow;
    int clickedColumn;
    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        txtNome.setText(txtNome.getText().trim());
        lblNome.setText(txtNome.getText());
        novaCategoria.setNome(txtNome.getText());
        txtGrupo.requestFocus();
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        txtNome.setText(txtNome.getText().trim());
        lblNome.setText(txtNome.getText());
        novaCategoria.setNome(txtNome.getText());
    }//GEN-LAST:event_txtNomeFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGrupo;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnResetar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cboxGrupo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNovoGrupo;
    private javax.swing.JLabel lblNovoIndicador;
    private javax.swing.JPanel paneTable;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}


class JTextHeader extends JTextField {

    public JTextHeader() {
        init();
    }

    public JTextHeader(String text) {
        super(text);
        init();
    }
    
    private void init() {
        setHorizontalAlignment(CENTER);
        setFont(new Font("SegoeUI", Font.BOLD, 14));
    }
}