/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.isa.view.indicadores;

import com.mycompany.isa.ISA;
import com.mycompany.isa.components.RefreshableJanela;
import com.mycompany.isa.model.Lote;
import com.mycompany.isa.model.CategoriaIndicadores;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class IndicadoresFrame extends RefreshableJanela {
    public static Lote lote;
    List<CategoriaIndicadores> categorias;
    CardLayout cl;
    int indice;
    String loteString = "<html>"
                    + "<b>Assentamento:</b> %s<br>"
                    + "<b>Responsável:</b>  %s<br>"
                    + "<b>Parcela:</b>      %s</html>";
    /**
     * Creates new form Indicadores
     */
    public IndicadoresFrame() {
        initComponents();
    }
    public IndicadoresFrame(Lote lote) {
        initComponents();
        IndicadoresFrame.lote = lote;
        refreshJanela();
    }
    
    private void atualizarBotoes() {
        btnAnterior.setEnabled(indice > 0);
        btnProximo.setEnabled(indice < categorias.size()-1);
    }
    
    @Override
    public void refreshJanela() {
        cl = (CardLayout) cardPane.getLayout();
        loteString = String.format(loteString, lote.getAssentamento(), lote.getResponsavel(), lote.getNumParcela());
        lblLoteNome.setText(loteString);
        categorias = ISA.categoriaList;
        if (categorias.isEmpty()) {
            indice = -1;
            JOptionPane.showMessageDialog(null, "Nenhuma categoria de indicadores cadastrada", "", JOptionPane.WARNING_MESSAGE);
        } else {
            indice = 0;
            for (CategoriaIndicadores categoria : categorias) {
                cardPane.add(new IndicadorCategoriaPanel(categoria), categoria.getNome());
            }
            cl.show(cardPane, categorias.get(indice).getNome());
        }
        atualizarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cardPane = new javax.swing.JPanel();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        lblLoteNome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnConcluir = new javax.swing.JToggleButton();
        standartMenuBar1 = new com.mycompany.isa.components.StandartMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ISA-RURAL");

        cardPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cardPane.setPreferredSize(new java.awt.Dimension(600, 420));
        cardPane.setLayout(new java.awt.CardLayout());

        btnAnterior.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAnterior.setText("<");
        btnAnterior.setEnabled(false);
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProximo.setText(">");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        lblLoteNome.setText("Lote");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnConcluir.setText("Concluir");
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(btnConcluir, gridBagConstraints);

        setJMenuBar(standartMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoteNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardPane, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardPane, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        indice += indice < categorias.size()-1 ? 1 : 0;
        cl.show(cardPane, categorias.get(indice).getNome());
        btnAnterior.setEnabled(true);
        btnProximo.setEnabled(false);
        atualizarBotoes();
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        indice -= (indice > 0) ? 1 : 0;
        cl.show(cardPane, categorias.get(indice).getNome());
        atualizarBotoes();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        ISA.trocarJanela(ISA.Janela.VER_INDICE);
    }//GEN-LAST:event_btnConcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndicadoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndicadoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndicadoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndicadoresFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndicadoresFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JToggleButton btnConcluir;
    private javax.swing.JButton btnProximo;
    private javax.swing.JPanel cardPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoteNome;
    private com.mycompany.isa.components.StandartMenuBar standartMenuBar1;
    // End of variables declaration//GEN-END:variables
}
