/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.isa.view.indicadores;

import com.mycompany.isa.model.CategoriaIndicadores;
import java.awt.*;
import java.util.List;

/**
 *
 * @author naoki
 */
public class IndicadorCategoriaPanel extends javax.swing.JPanel {
    CategoriaIndicadores categoria;
    static int currentRow;
    /**
     * Creates new form IndicadorTabelaPanel
     */
    public IndicadorCategoriaPanel() {
        initComponents();
    }
    
    public IndicadorCategoriaPanel(CategoriaIndicadores categoria) {
        this.categoria = categoria;
        initAll();
    }
    
    private void initAll() {
        currentRow = 0;
        IndicadoresFrame.lote.initScoreSheet(categoria);
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
        String[] gruposNome = categoria.getGrupos().toArray(String[]::new);
        List<List<String>> items = categoria.getAllItems();
        for (int i=0; i<gruposNome.length; i++) {
            String[] itemArr = items.get(i).toArray(String[]::new);
            IndicadorGrupoPanel grupo = new IndicadorGrupoPanel(currentRow, gruposNome[i],itemArr, categoria.getNome().hashCode());
            gruposPanel.add(grupo);
            GridBagLayout layout = (GridBagLayout) gruposPanel.getLayout();
            GridBagConstraints c = layout.getConstraints(grupo);
            c.insets = new Insets(0, 0, 0, 0);
            c.gridy = i;
            layout.setConstraints(grupo, c);
            
            grupo.getLblNumGrupo().addPropertyChangeListener("text", (evt) -> {
                lblIndice.setText(String.format("%.3f", IndicadoresFrame.lote.calcularIndiceCategoria(categoria.getNome().hashCode())));
            });
            grupo.setVisible(true);
        }
        lblIndice.setText(String.format("%.3f", IndicadoresFrame.lote.calcularIndiceCategoria(categoria.getNome().hashCode())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblIndicadores = new javax.swing.JLabel();
        lblParametros = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gruposPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblIndice = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 420));

        lblIndicadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIndicadores.setText("Indicadores");

        lblParametros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblParametros.setText("Parâmetros");

        lblNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNum.setText("Nº");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(categoria.getNome());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblIndicadores)
                .addGap(153, 153, 153)
                .addComponent(lblParametros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(lblNum)
                .addGap(15, 15, 15))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIndicadores)
                    .addComponent(lblParametros)
                    .addComponent(lblNum))
                .addContainerGap())
        );

        gruposPanel.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(gruposPanel);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Média Geral:");

        lblIndice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIndice.setText("0.0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblIndice)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIndice))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gruposPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIndicadores;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblParametros;
    // End of variables declaration//GEN-END:variables
}
