/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.Map;
import javax.swing.SwingConstants;
import javax.swing.table.*;
import model.IndicadoresModelo;

/**
 *
 * @author naoki
 */
public class NovoModelo extends javax.swing.JPanel {
    IndicadoresModelo novoModelo = new IndicadoresModelo();
    /**
     * Creates new form NovoModelo
     */
    public NovoModelo() {
        initAll();
    }
    
    public NovoModelo(IndicadoresModelo modelo) {
        initAll();
        novoModelo = modelo;
        lblNome.setText(modelo.getNome());
        preencherTabela();
    }
    

    private void initAll() {
        initComponents();
        preencherTabela();
        mostrarDadosTela();
        
        header = tabModelo.getTableHeader();
        header.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent event) {
                if (event.getClickCount() > 1)
                    editColumnAt(event.getPoint());
            }
        });

        txtEditHeader.setBorder(null);
    }

    private void mostrarDadosTela() {
        int grupoSelecionado = tabModelo.getSelectedColumn();
        int itemSelecionado = tabModelo.getSelectedRow();
        txtNome.setText(novoModelo.getNome());
        if (grupoSelecionado == -1) {
            txtGrupo.setText("");
            cboxGrupo.setSelectedIndex(0);
        } 
        else {
            txtGrupo.setText(novoModelo.getGrupos().get(grupoSelecionado));
            cboxGrupo.setSelectedIndex(0);
        }
    }
    private void preencherTabela() {
        
        DefaultTableCellRenderer cellRender = new DefaultTableCellRenderer();
	cellRender.setHorizontalAlignment(SwingConstants.CENTER);
        tabModelo.getColumnModel().getColumn(0).setPreferredWidth(100);  //Preferencia de largura medidad em pixels
        tabModelo.getColumnModel().getColumn(1).setPreferredWidth(100);  
        tabModelo.getColumnModel().getColumn(2).setPreferredWidth(100);  
        tabModelo.getColumnModel().getColumn(3).setPreferredWidth(100);
        for (int i=0; i<tabModelo.getColumnCount(); i++)
            tabModelo.getColumnModel().getColumn(i).setCellRenderer(cellRender);
        
        DefaultTableModel modelo = (DefaultTableModel) tabModelo.getModel();
        modelo.setNumRows(0);
        for (Map.Entry grupo: novoModelo.getIndicadores().entrySet()) {
            modelo.addColumn(grupo.getKey(), ((List<String>) grupo.getValue()).toArray());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEditHeader = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblTitleNovo = new javax.swing.JLabel();
        btnAddGrupo = new javax.swing.JButton();
        txtGrupo = new javax.swing.JTextField();
        lblNovoGrupo = new javax.swing.JLabel();
        lblNovoIndicador = new javax.swing.JLabel();
        txtItem = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        cboxGrupo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        scrollTabela = new javax.swing.JScrollPane();
        tabModelo = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();

        txtEditHeader.setText("jTextField1");
        txtEditHeader.setBorder(null);
        txtEditHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditHeaderActionPerformed(evt);
            }
        });

        txtNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do modelo"));
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });

        lblTitleNovo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleNovo.setText("Criar novo modelo");

        btnAddGrupo.setText("Adicionar Grupo ao modelo");
        btnAddGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGrupoActionPerformed(evt);
            }
        });

        txtGrupo.setToolTipText("Escreva o nome do grupo");

        lblNovoGrupo.setText("Novo grupo");

        lblNovoIndicador.setText("Novo indicador");

        txtItem.setToolTipText("Escreva o nome do indicador");

        btnAddItem.setText("Adicionar indicador ao grupo");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        cboxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecionar Grupo>" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Salvar");

        scrollTabela.setBackground(new java.awt.Color(255, 255, 204));
        scrollTabela.setForeground(new java.awt.Color(0, 204, 204));
        scrollTabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tabModelo.setToolTipText("Clique duas vezes para editar");
        tabModelo.setShowGrid(false);
        tabModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabModeloMouseClicked(evt);
            }
        });
        tabModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabModeloKeyReleased(evt);
            }
        });
        scrollTabela.setViewportView(tabModelo);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Nome do modelo");
        lblNome.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblTitleNovo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtGrupo)
                            .addComponent(btnAddGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtItem)
                            .addComponent(btnAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(cboxGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNovoGrupo)
                                    .addComponent(lblNovoIndicador))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollTabela)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleNovo)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNovoGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddGrupo)
                        .addGap(18, 18, 18)
                        .addComponent(lblNovoIndicador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editColumnAt(Point p) {
        int columnIndex = header.columnAtPoint(p);

        if (columnIndex != -1){
            column = header.getColumnModel().getColumn(columnIndex);
            Rectangle columnRectangle = header.getHeaderRect(columnIndex);

            txtEditHeader.setText(column.getHeaderValue().toString());
            renamePopup.setPreferredSize(
                new Dimension(columnRectangle.width, columnRectangle.height - 1));
            renamePopup.show(header, columnRectangle.x, 0);

            txtEditHeader.requestFocusInWindow();
            txtEditHeader.selectAll();
        }
     }

    private void renameColumn() {
        column.setHeaderValue(txtEditHeader.getText());
        renamePopup.setVisible(false);
        header.repaint();
    }
  
    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        String nome = txtNome.getText();
        novoModelo.setNome(nome);
    }//GEN-LAST:event_txtNomeFocusLost

    private void btnAddGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGrupoActionPerformed
        String grupo = txtGrupo.getText();
        txtGrupo.setText("");
        if (! novoModelo.getIndicadores().containsKey(grupo)){
            novoModelo.addGrupo(grupo);
            cboxGrupo.addItem(grupo);
        }
    }//GEN-LAST:event_btnAddGrupoActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        String grupo = (String) cboxGrupo.getSelectedItem();
        String item = txtItem.getText();
        if (novoModelo.getIndicadores().containsKey(grupo)) {
            if (! novoModelo.getItens(grupo).contains(item)) {
                novoModelo.addItem(grupo, item);
            }
        }
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void tabModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabModeloMouseClicked
        if (evt.getClickCount() > 1) {
            int rowIndex = tabModelo.rowAtPoint(evt.getPoint());
            if (rowIndex < 0) {
                
            } 
            else {
                
            }
        }
        mostrarDadosTela(indice);
        atualizarBotoes();
    }//GEN-LAST:event_tabModeloMouseClicked

    private void tabModeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabModeloKeyReleased

        mostrarDadosTela(indice);
        atualizarBotoes();
    }//GEN-LAST:event_tabModeloKeyReleased

    private void txtEditHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditHeaderActionPerformed
        column.setHeaderValue(txtEditHeader.getText());
        renamePopup.setVisible(false);
        header.repaint();
    }//GEN-LAST:event_txtEditHeaderActionPerformed
    
    private javax.swing.JPopupMenu renamePopup;
    private javax.swing.table.TableColumn column;
    private javax.swing.table.JTableHeader header;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGrupo;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JComboBox<String> cboxGrupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNovoGrupo;
    private javax.swing.JLabel lblNovoIndicador;
    private javax.swing.JLabel lblTitleNovo;
    private javax.swing.JScrollPane scrollTabela;
    private javax.swing.JTable tabModelo;
    private javax.swing.JTextField txtEditHeader;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtItem;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
